# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PANZ - Pan Australia and New Zealand
email: renwooller@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The home for Steelbands and Steelpan Players in Australia & New Zealand.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.panz.org.au" # the base hostname & protocol for your site
#twitter_username: 
github_username:  renewooller

# Build settings
markdown: kramdown
